server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: jiang
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast
    ttl: 3600000
feign:   #熔断器 默认是关闭的
 hystrix:
    enabled: true;