server:
  port: 9010
spring:
  application:
    name: tensquare-friend #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_friend?characterEncoding=UTF8
    username: root
    password: jiang
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast
